server {
    listen 80;
    root /usr/share/nginx/html;

    # site.html est la page d'accueil (vitrine thématisée)
    index site.html;

    location / {
        try_files $uri $uri/ /site.html;
    }

    # Gzip
    gzip on;
    gzip_types text/html text/css application/javascript image/svg+xml;
}
